spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 0883aee8328051757642
            client-secret: 5dfbebc657bfaca0318b782a0cf63222c44cd036

#logging:
#  level:
#    org.springframework.security: DEBUG
